version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: &kafka-image bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 5

  init-kafka:
    image: *kafka-image
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --topic myTopic --replication-factor=1 --partitions=1 --bootstrap-server=kafka:9092 &&
      echo 'Topic myTopic created'
      "
